options:
  formatter: stylish
  merge-default-rules: true
rules:
  border-zero: 0
  class-name-format:
    - 1
    - convention: '[uicc|is-].\w+'
  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[uicc|_].\w+'
  id-name-format:
    - 1
    - convention: '^[uicc|is-].\w+$'
  leading-zero: 0
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[uicc|_].\w+'
  no-css-comments: 0
  no-trailing-zero: 0
  placeholder-name-format:
    - 1
    - convention: '[uicc|is-].\w+'
  property-sort-order: 0
  shorthand-values: 0
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[uicc|_].\w+'
  zero-unit: 0
  empty-args: 0
  force-pseudo-nesting: 0
